### ISSUE TITLE
原来是两张图片叠合在一起的，惊呆了！

### ISSUE THREAD

**Issue by 401885064** [wl9739/BlurredView#2]
原本想了解下RenderScript是怎么模糊图片，确实学到东西了，谢谢作者。
但为什么要用两张图片去实现？？   不是可以改成一张图片进行模糊吗？  为了性能？

**Comment by eateeer** [comment]
确实是为了性能。因为即使用了RenderScript，也没办法保证在中低端手机上实时模糊的流畅性。详细情况可以参考我的博客：[http://blog.csdn.net/wl9739/article/details/51955598](http://blog.csdn.net/wl9739/article/details/51955598)。

**Comment by W-quan** [comment]
按你的做法，岂不是可以直接ps出一张模糊过的图片来，连使用RenderScript来模糊都省了。

**Comment by eateeer** [comment]
当然可以，如果使用场景允许这么做的话。

**Comment by yinyinnie** [comment]
Hi, there! Possibly, the way will cause OOM easily because it will have two pics in Memory .  How can I deal with it?
