### ISSUE TITLE
在5.0系统上报错

### ISSUE THREAD

**Issue by pengbs** [wl9739/BlurredView#3]
我使用你这个库，在5.0上报这个错： android.support.v8.renderscript.RSRuntimeException: Error loading RS jni library: java.lang.UnsatisfiedLinkError: dlopen failed: library "/data/app/xxx-2/lib/arm/librsjni.so" not found Support lib API: 2301，请问你知道怎么解决吗？

**Comment by eateeer** [comment]
你的 build tools版本号是多少？版本号太低会有问题，建议升级至Build Tools, Revision 23.0.3 以上。

**Comment by pengbs** [comment]
谢谢你的关注，我的compileSdkVersion是23，build tools是23.0.3

**Comment by eateeer** [comment]
在defaultconfig里面加下面的代码试试

``` java
ndk {
    abiFilters "armeabi","armeabi-v7a", "x86", "mips"
}
```

**Comment by pengbs** [comment]
好的，我试试看
